name: Vipin Pull Request Management GitHub Action
author: vipinkrajput
description: Github action for Pull Request management (Auto assignment of reviewers, requesting reviews on pull request)

inputs:
  reviewers:
    description: 'Comma separated list of reviewers'
    required: true
  
  repository:
    description: 'Repository name'
    required: false
    default: ${{ github.repository }}     

outputs:
  message:
    description: 'Greeting Message'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.reviewers }}
  
branding:
  icon: "git-pull-request"
  color: "purple"