name: Code Review GitHub Action
author: vipinkrajput
description: Github action for assigning reviewers, requesting reviews automatically on pull request

inputs:
  reviewers:
    description: 'List of reviewers'
    required: true
  
  repository:
    description: 'Repository name'
    required: false
    default: ${{ github.repository }}     

outputs:
  message:
    description: 'Greeting Message'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.reviewers }}
  